### ISSUE TITLE
I have some issues.

### ISSUE THREAD

**Issue by ReXulEc** [alexmilde/vue-gradient#1]
Hi i am new at vue.js . I have some problems. I cant type up to the gradient. Can you help please
Best regards
-ReXulEc / Mert Doğu

**Comment by alexmilde** [comment]
Can you post your code or a codepen?

**Comment by ReXulEc** [comment]
It's been a long time, but I solved the problem, thank you very much! <33

**Comment by alexmilde** [comment]
Hey, no worries.
For future issues (and this one aswell) it would be nice if you describe your issue AND post your solution aswell. Other users might appreciate this.
